### ISSUE TITLE
Could not start com.apple.debugserver!

### ISSUE THREAD

**Issue by Sparcks** [ios-driver/libimobiledevice-wrapper#17]
Hi

I'm getting: Could not start com.apple.debugserver!
I have mounted the DeveloperDiskImage (I think, not getting any feedback/output saying that it worked).
The images files are in the same directory as ideviceimagemounter.

I wrote a method in csharp that starts the exe with arguments:
StartCommand(@"tools/ios/ideviceimagemounter.exe", "--udid \"" + deviceName + "\" --imagetype Developer DeveloperDiskImage.dmg DeveloperDiskImage.dmg.signature --debug");

Now, when I want to run my app, it says it can't.
I do have to say that I have iOS version: 9.2.1, but could only find 9.2 disk image on my mac.
Seems that there are no X.Y.Z disk images, only X.Y ones.

Could this be the problem?
If so, how can Xcode ever run their apps if there is no developer disk image for those version?

Thanks in advance.

**Comment by Sparcks** [comment]
This github page links to http://quamotion.mobi/iMobileDevice, right?

**Comment by lukeis** [comment]
no, that appears to be https://github.com/libimobiledevice

**Comment by Sparcks** [comment]
Ow, ok.
Sorry for posting in the wrong place then.
